/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package flink.parquet.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface FlinkParquetAvro {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"FlinkParquetAvro\",\"namespace\":\"flink.parquet.avro\",\"types\":[{\"type\":\"enum\",\"name\":\"PhoneType\",\"symbols\":[\"MOBILE\",\"HOME\",\"WORK\"]},{\"type\":\"record\",\"name\":\"PhoneNumber\",\"fields\":[{\"name\":\"number\",\"type\":\"string\"},{\"name\":\"type\",\"type\":[\"PhoneType\",\"null\"],\"default\":\"HOME\"}]},{\"type\":\"record\",\"name\":\"Person\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"email\",\"type\":[\"string\",\"null\"]},{\"name\":\"phone\",\"type\":{\"type\":\"array\",\"items\":\"PhoneNumber\"}}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends FlinkParquetAvro {
    public static final org.apache.avro.Protocol PROTOCOL = flink.parquet.avro.FlinkParquetAvro.PROTOCOL;
  }
}