/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package flink.parquet.avro;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PhoneNumber extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1709638050328921123L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PhoneNumber\",\"namespace\":\"flink.parquet.avro\",\"fields\":[{\"name\":\"number\",\"type\":\"string\"},{\"name\":\"phoneType\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"PhoneType\",\"symbols\":[\"MOBILE\",\"HOME\",\"WORK\"]}],\"default\":\"HOME\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence number;
  @Deprecated public flink.parquet.avro.PhoneType phoneType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PhoneNumber() {}

  /**
   * All-args constructor.
   * @param number The new value for number
   * @param phoneType The new value for phoneType
   */
  public PhoneNumber(java.lang.CharSequence number, flink.parquet.avro.PhoneType phoneType) {
    this.number = number;
    this.phoneType = phoneType;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return number;
    case 1: return phoneType;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: number = (java.lang.CharSequence)value$; break;
    case 1: phoneType = (flink.parquet.avro.PhoneType)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'number' field.
   * @return The value of the 'number' field.
   */
  public java.lang.CharSequence getNumber() {
    return number;
  }

  /**
   * Sets the value of the 'number' field.
   * @param value the value to set.
   */
  public void setNumber(java.lang.CharSequence value) {
    this.number = value;
  }

  /**
   * Gets the value of the 'phoneType' field.
   * @return The value of the 'phoneType' field.
   */
  public flink.parquet.avro.PhoneType getPhoneType() {
    return phoneType;
  }

  /**
   * Sets the value of the 'phoneType' field.
   * @param value the value to set.
   */
  public void setPhoneType(flink.parquet.avro.PhoneType value) {
    this.phoneType = value;
  }

  /**
   * Creates a new PhoneNumber RecordBuilder.
   * @return A new PhoneNumber RecordBuilder
   */
  public static flink.parquet.avro.PhoneNumber.Builder newBuilder() {
    return new flink.parquet.avro.PhoneNumber.Builder();
  }

  /**
   * Creates a new PhoneNumber RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PhoneNumber RecordBuilder
   */
  public static flink.parquet.avro.PhoneNumber.Builder newBuilder(flink.parquet.avro.PhoneNumber.Builder other) {
    return new flink.parquet.avro.PhoneNumber.Builder(other);
  }

  /**
   * Creates a new PhoneNumber RecordBuilder by copying an existing PhoneNumber instance.
   * @param other The existing instance to copy.
   * @return A new PhoneNumber RecordBuilder
   */
  public static flink.parquet.avro.PhoneNumber.Builder newBuilder(flink.parquet.avro.PhoneNumber other) {
    return new flink.parquet.avro.PhoneNumber.Builder(other);
  }

  /**
   * RecordBuilder for PhoneNumber instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PhoneNumber>
    implements org.apache.avro.data.RecordBuilder<PhoneNumber> {

    private java.lang.CharSequence number;
    private flink.parquet.avro.PhoneType phoneType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(flink.parquet.avro.PhoneNumber.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.number)) {
        this.number = data().deepCopy(fields()[0].schema(), other.number);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.phoneType)) {
        this.phoneType = data().deepCopy(fields()[1].schema(), other.phoneType);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PhoneNumber instance
     * @param other The existing instance to copy.
     */
    private Builder(flink.parquet.avro.PhoneNumber other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.number)) {
        this.number = data().deepCopy(fields()[0].schema(), other.number);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.phoneType)) {
        this.phoneType = data().deepCopy(fields()[1].schema(), other.phoneType);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'number' field.
      * @return The value.
      */
    public java.lang.CharSequence getNumber() {
      return number;
    }

    /**
      * Sets the value of the 'number' field.
      * @param value The value of 'number'.
      * @return This builder.
      */
    public flink.parquet.avro.PhoneNumber.Builder setNumber(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.number = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'number' field has been set.
      * @return True if the 'number' field has been set, false otherwise.
      */
    public boolean hasNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'number' field.
      * @return This builder.
      */
    public flink.parquet.avro.PhoneNumber.Builder clearNumber() {
      number = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'phoneType' field.
      * @return The value.
      */
    public flink.parquet.avro.PhoneType getPhoneType() {
      return phoneType;
    }

    /**
      * Sets the value of the 'phoneType' field.
      * @param value The value of 'phoneType'.
      * @return This builder.
      */
    public flink.parquet.avro.PhoneNumber.Builder setPhoneType(flink.parquet.avro.PhoneType value) {
      validate(fields()[1], value);
      this.phoneType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'phoneType' field has been set.
      * @return True if the 'phoneType' field has been set, false otherwise.
      */
    public boolean hasPhoneType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'phoneType' field.
      * @return This builder.
      */
    public flink.parquet.avro.PhoneNumber.Builder clearPhoneType() {
      phoneType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public PhoneNumber build() {
      try {
        PhoneNumber record = new PhoneNumber();
        record.number = fieldSetFlags()[0] ? this.number : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.phoneType = fieldSetFlags()[1] ? this.phoneType : (flink.parquet.avro.PhoneType) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
